parser: '@typescript-eslint/parser'

extends:
  - 'plugin:prettier/recommended'
  - 'eslint:recommended'

plugins:
  - 'babel'
  - 'prettier'

env:
  browser: true
  node: true
  mocha: true
  es6: true

globals:
  io: readonly
  '^G_': writeable

ignorePatterns:
  - main.js
  - public

rules:
  prettier/prettier:
    - 2
    - bracketSpacing: true
      singleQuote: true
      tabWidth: 2
      trailingComma: 'es5'
  no-lone-blocks: 0
  no-throw-literal: 0
  no-console: 0
  no-case-declarations: 0
  no-fallthrough: 0
  no-sparse-arrays: 0
  new-cap: 0
  react/jsx-pascal-case: 0
  react/jsx-no-undef: 0
  no-undef: 0    
  no-unused-vars:
    - 0
    - vars: 'local'
      varsIgnorePattern: '^G_'
  '@typescript-eslint/no-unused-vars':
    - 0
    - vars: 'local'
      varsIgnorePattern: '^G_'
