parser: 'babel-eslint'

extends:
  - 'react-app'
  - 'plugin:prettier/recommended'

plugins:
  - 'babel'
  - 'prettier'
  - 'mocha'

settings:
  react:
    version: 'detect'

env:
  browser: true
  mocha: true

rules:
  prettier/prettier:
    - 2
    - bracketSpacing: true
      singleQuote: true
      tabWidth: 2
      trailingComma: 'es5'
  no-lone-blocks: 0
  no-throw-literal: 0
