extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'

env:
  browser: true

rules:
  no-lone-blocks: 0
  no-throw-literal: 0
  indent: 0
  brace-style: 0
  no-unused-vars: 1
  no-var: 0
  object-shorthand: 0
  '@typescript-eslint/no-empty-function': 0
  radix: 0
  no-lonely-if: 0
  no-else-return: 0
  func-style: 0
